all:
	gcc -O4 -ansi -Wall -c -o life.o life.c
	gcc -O4 -ansi -Wall -c -o genetic.o genetic.c
	gcc -O4 -ansi -Wall -c -o dnalife.o dnalife.c
	gcc -O4 -ansi -Wall -o dnalife dnalife.o genetic.o life.o
clean:
	rm *.o


